language: scala
env:
  - PLAY_VERSION=2.1.1
before_script: 
  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip 
script:
  - play-${PLAY_VERSION}/play jacoco:cover
  - _JAVA_OPTIONS="-Dsbt.main.class=sbt.ScriptMain" play coveralls
  - cat target/coveralls.json
notifications:
  email: false
